//
//  ViewController.swift
//  BillOrSteve
//
//  Created by James Campagno on 6/8/16.
//  Copyright © 2016 Flatiron School. All rights reserved.
//

import UIKit

class ViewController: UIViewController {
    
    var steveBillFacts: [String : [String]] = [:]
    var counter = 0
    var totalQuestionsAsked = 0
    var correctAnswer: String = ""
    
    @IBOutlet weak var factLabel: UILabel!
    @IBOutlet weak var scoreCounter: UILabel!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        generateFacts()
        showFact()
    }
    
    @IBAction func steveButton(sender: AnyObject) {
            if correctAnswer == "Steve Jobs" {
            counter += 1
            totalQuestionsAsked += 1
            let counterString = "\(counter) / \(totalQuestionsAsked)"
            scoreCounter.text = counterString
        } else {
            totalQuestionsAsked += 1
            let counterString = "\(counter) / \(totalQuestionsAsked)"
            scoreCounter.text = counterString

        }
        showFact()
    }
    
    @IBAction func billButton(sender: AnyObject) {
            if correctAnswer == "Bill Gates" {
            counter += 1
            totalQuestionsAsked += 1
            let counterString = "\(counter) / \(totalQuestionsAsked)"
            scoreCounter.text = counterString
        } else {
            totalQuestionsAsked += 1
            let counterString = "\(counter) / \(totalQuestionsAsked)"
            scoreCounter.text = counterString

        }
        showFact()
    }
    
    func generateFacts() {
        steveBillFacts =  ["Steve Jobs":
        ["He took a calligraphy course, which he says was instrumental in the future company products' attention to typography and font.",
        "Shortly after being shooed out of his company, he applied to fly on the Space Shuttle as a civilian astronaut (he was rejected) and even considered starting a computer company in the Soviet Union.",
        "He actually served as a mentor for Google founders Sergey Brin and Larry Page, even sharing some of his advisers with the Google duo.",
        "He was a pescetarian, meaning he ate no meat except for fish."],
        "Bill Gates": [
        "He aimed to become a millionaire by the age of 30. However, he became a billionaire at 31.",
        "He scored 1590 (out of 1600) on his SATs.",
        "His foundation spends more on global health each year than the United Nation's World Health Organization.",
        "The private school he attended as a child was one of the only schools in the US with a computer. The first program he ever used was a tic-tac-toe game.",
        "In 1994, he was asked by a TV interviewer if he could jump over a chair from a standing position. He promptly took the challenge and leapt over the chair like a boss."]]
    }

   
    

    func randomNumberFromZeroTo(number: Int) -> Int {
        
        return Int(arc4random_uniform(UInt32(number)))
        
    }
    
    func randomPerson() -> String {
        
        let randomNumber = arc4random_uniform(2)
        
        if randomNumber == 0 {
            return "Steve Jobs"
        } else {
            return "Bill Gates"
        }
        
    }
    
    
    func getRandomFact() -> (name: String, fact: String) {
        
        var message: (String, String) = ("", "")
        
        let randName = randomPerson() // "Steve Jobs"
        
        if let factsCalled = steveBillFacts[randName] { // ["facts", "facts", "facts"]
        
            let randNum = randomNumberFromZeroTo(factsCalled.count) // picks # from 0 to amount of facts
            
            let randFact = factsCalled[randNum] // calls one fact from array at index# generated by random number
            
            message = (randName, randFact) //stores name and fact in tuple message variable
            
        }
        return message // returns name and fact
    }
    
    
    
    func showFact() {
        let nameAndFact = getRandomFact() // name and the fact
        let factForLabel = nameAndFact.fact //save fact from message as new variable
        factLabel.text = factForLabel // update label with new fact
        let answerForChecking = nameAndFact.name // saves name from message as answer
        correctAnswer = answerForChecking // store in instance variable set at beginning
        }
    
    
    }